### ISSUE TITLE
[Docs] [Bitmark references] - SDK document

### ISSUE THREAD

**Issue by vienlt** [bitmark-inc/docs#10]
@jollyjoker992 
- [ ] reviewed & revised descriptions
- [ ] add code examples for Android/Java

@anhnguyenbitmark 
- [ ] reviewed & revised descriptions 

@cuongleqq 
- [ ] reviewed & revised descriptions

@nodestory  
- [x] reviewed & revised descriptions

Please finish the review by the end of 9/6.

**Comment by vienlt** [comment]
@anhnguyenbitmark, @jollyjoker992, @nodestory: Could you discuss and assign the subtasks?

**Comment by anhnguyenbitmark** [comment]
Checking if jekyll can render code blocks for sdk docs.
