### ISSUE TITLE
[Docs] [Learning Bitmark] - Contributing to Bitmark

### ISSUE THREAD

**Issue by vienlt** [bitmark-inc/docs#7]
Provide content for (but not limited to) the following subsections 

- [x]  BUP - Bitmark Upgrade Proposal
- [x] How to files issues on Github
- [ ] How to file issues on github.

**Comment by araujobsd** [comment]
Discussed with Vien:
Related to the documentation, community section, we listed an bullet as How to file issues on github. Is it covered by the development process document?

Me: I will add an issue template as a reference.
